### ISSUE TITLE
BLURB for Homepage: Need attention attracting sentence for the three main services

### ISSUE THREAD

**Issue by iandstanley** [stereocats/jenniferbrickwell#106]
Jennifer 

I need a sentence a short paragraph for the back of the cards (when they flip over when hovered over) for each of the service groups

- Events
- Conferences
- Training

**Comment by jenniferbrickwell** [comment]
Slide 1
We are an event management company that deliver a wide-range of bespoke events at competitive prices. No event is too big or too small and we are able to create unique events packages to suit your specific needs. We offer a range of services and are able to plan all aspects of your event leaving you to relax and enjoy your special occasion.

**Comment by jenniferbrickwell** [comment]
Slide 2
We understand the need to create engaging, relevant and interactive conferences that will be both inspiring and informative. Whether it is a symposium or seminar, we can assist you in all aspects of conference management to ensure that your event is a success and achieves its objectives.
