### ISSUE TITLE
BLURB for EVENTS page: Text needed for hero image

### ISSUE THREAD

**Issue by iandstanley** [stereocats/jenniferbrickwell#108]
This is the heading and text in the image just below the navigation (contains background image of a conference

**Comment by iandstanley** [comment]
@jenniferbrickwell I have added a single sentence to the hero image for now. Please let me know if/how you want to change it

**Comment by jenniferbrickwell** [comment]
Can I see the full events page?

**Comment by jenniferbrickwell** [comment]
Slide 1
We are an event management company that deliver a wide-range of bespoke events at competitive prices. No event is too big or too small and we are able to create unique events packages to suit your specific needs. We offer a range of services and are able to plan all aspects of your event leaving you to relax and enjoy your special occasion.
