### ISSUE TITLE
BLURB for EVENTS: Text needed for Pharmaceutical

### ISSUE THREAD

**Issue by iandstanley** [stereocats/jenniferbrickwell#111]

**Comment by jenniferbrickwell** [comment]
Pharmaceutical
Having worked for over 10 years in the pharmaceutical industry specialising in clinical research, we have key in-depth knowledge and experience in all phases of drug development and understand the clinical programme, regulatory and safety issues that often need to be addressed. We  therefore can create tailor-made events to suit your specific needs.
