### ISSUE TITLE
BLURB for EVENTS: Lead for Contact Us form

### ISSUE THREAD

**Issue by iandstanley** [stereocats/jenniferbrickwell#114]

**Comment by jenniferbrickwell** [comment]
Contact Us 
To discuss your training needs in more detail, please contact us below. We look forward to helping you and your organisation achieve its learning and development objectives.
(training only)

Contact Us
Get in touch with us today and let us assist you in creating that memorable event. We would welcome the opportunity to discuss your event with you.

**Comment by iandstanley** [comment]
done
