### ISSUE TITLE
BLURB for Training: Text needed for process workshops

### ISSUE THREAD

**Issue by iandstanley** [stereocats/jenniferbrickwell#115]

**Comment by jenniferbrickwell** [comment]
Training
With continually changing regulations and standards, it is difficult to find time to keep up-to-date. We offer cost-effective training programs that deliver the knowledge and skills that you and your team require to keep you both well-informed and to maintain your competitive edge. 
Venues are thoroughly researched to ensure training is conducted in a comfortable and friendly learning environment.
 Training covers a wide-range of subjects including soft-skills to key technical skills required in the pharmaceutical industry.

**Comment by jenniferbrickwell** [comment]
text above to be added to Process workshop. Please change title to Training Workshops

**Comment by iandstanley** [comment]
Done
