### ISSUE TITLE
Family Events

### ISSUE THREAD

**Issue by jenniferbrickwell** [stereocats/jenniferbrickwell#130]
Family Events
No matter how big or small your personal event, we offer a full range of service for all types of occasions. We can tailor a package to meet your needs and budget and with attention to detail, we will cover all aspects of planning and running your event to ensure that it is a smooth and memorable occasion.

_This can be used for a slider or anywhere else that it is appropriate

**Comment by iandstanley** [comment]
Added to slide 3 (wedding style event)
