### ISSUE TITLE
Director photo!

### ISSUE THREAD

**Issue by jenniferbrickwell** [stereocats/jenniferbrickwell#131]
![aimg_1435_edited-1](https://cloud.githubusercontent.com/assets/20337112/16985101/3120a41c-4e76-11e6-969c-6015e64714d9.jpg)
![aimg_1505_edited-1](https://cloud.githubusercontent.com/assets/20337112/16985105/38b8bc82-4e76-11e6-8d86-20ff08f6cd3b.jpg)

Hope this worked. Probably the photo of me sitting at a desk is best.

**Comment by iandstanley** [comment]
Actually the top one is a far better photo (speaking as an ex-pro photographer)

**Comment by iandstanley** [comment]
Should I be adding this in the contact us section?

**Comment by jenniferbrickwell** [comment]
Yes add this to the contact section. Question- is it possible to photoshop the mark out of the window on the LHS?

**Comment by iandstanley** [comment]
See also #150 bio to add with photo ...
