### ISSUE TITLE
Bio to accompany photo

### ISSUE THREAD

**Issue by jenniferbrickwell** [stereocats/jenniferbrickwell#150]
Jennifer is a qualified Project Manager and Event Planner who has nearly 18 years experience working in a variety of roles in the pharmaceutical industry, academic and the charity sectors. She runs Jennifer Brickwell Event Management Limited which specialises in bespoke events that create influence and impact.

**Comment by iandstanley** [comment]
See photos in issue #131

**Comment by iandstanley** [comment]
![jennifer](https://cloud.githubusercontent.com/assets/6939289/17889323/81ff8134-6927-11e6-849f-3f83f4f51a6e.jpg)

**Comment by iandstanley** [comment]
![jennifer](https://cloud.githubusercontent.com/assets/6939289/17961222/5737ae82-6aa2-11e6-82df-4e67bcd3887f.jpg)
pushed this photo live
