### ISSUE TITLE
Conference and Event management page split

### ISSUE THREAD

**Issue by jenniferbrickwell** [stereocats/jenniferbrickwell#151]
Would be good to discuss this:
Community events would be better placed on the event management page along with family events.

Conferences, academic etc work best just on the conference page.

**Comment by iandstanley** [comment]
You wanted to chat about this @jenniferbrickwell

**Comment by iandstanley** [comment]
Will need to discuss later the layout and content for community

for now I have just pushed the community chunk from event management on it

If you have any ideas @jennifer whilst I am away just create a new issue
