### ISSUE TITLE
add Rob&Ray quotes to testimony 1

### ISSUE THREAD

**Issue by iandstanley** [stereocats/jenniferbrickwell#173]
- [x] Jennifer to send new and better picture

**Comment by jenniferbrickwell** [comment]
Photo of the event. Feel free to remove me if this means you have a better quality photo.
![2010-01-27 14 18 23-165](https://cloud.githubusercontent.com/assets/20337112/17889563/b8e09f16-6928-11e6-86d0-4aa009233a55.jpg)
