### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by jenniferbrickwell** [stereocats/jenniferbrickwell#178]
Hi
 Please can you make the following very minor amendments. I have included comments from a reviewer. Very positive feedback from several people including my business coach so well done. Good job :). Very impresssive.

Home Page
1. Training Service button- spell check more
2.First testimonials-  I'd- to remove additional space.
MP after Rob Wilson

Conferences
Please amend event management to conference management
The last picture on this page http://jenniferbrickwellevents.com/conferences.html is a bit soft and looks like it is out of focus rather than softened to obscure the word CBI on the podium.

Community
Please amend text on main photo to read- We manage a wide variety of family and community events. We can take care of your event to ensure that it is stress-free and successful.

Can you add a family event photo on that page- maybe the same one or similar to the one in the 3 top photos (dining photo). Please add the following text to go with the family photo- If you are looking for an event to celebrate a special occasion, we can assist you with all aspects of event management to ensure that it is a unique and memorable occasion.

Training - would love a better main photo if possible. Any ideas?

Has your website designer checked it so that it displays properly on different size screens? It displays fine on my phone, and on my Surface but when I had it on my big screen 24" Dell it doesn't display properly and the titles crash into the images
Is it possible to slow down the text over the main photos slightly?
The comment on the footer, "...feel free to contact us..." should have a mailto: link on it or you should transpose the link on the other side. I am a great fan of having as many opportunities as possible to have contact me.

Hope this is clear.
Thanks 
Jennifer

**Comment by iandstanley** [comment]
I know it doesn't display properly over 1280 pixels wide and have yet to encompass a container around each page for wider browsers (approximately 20% of page views). Intend to put wrapper in this week ideally later today - failing that sat evening

**Comment by iandstanley** [comment]
Closed issue in favour of individual issues #179 #180 #181 #182 #183 #184 #185  #186 #187
