### ISSUE TITLE
Logo amendments for pop-up banner

### ISSUE THREAD

**Issue by jenniferbrickwell** [stereocats/jenniferbrickwell#215]
Hi Ian,
Thanks for looking into this. This is the email I receive from Blue Moose Printing who will be at the Festival.

_Thank you for sending your images over earlier. They’re not quite in the correct format for us to be able to print from.
Are you able to forward the attached template and guideline on to the person that creates your artwork please so that it can all be set to the correct size and spec?
If it doesn’t quite make sense, please let me know and I can go through it with you / them.
Kind regards,
Mike_
Tel: 0118 934 5016
Email: sales@thebmgc.com
[Grasshopper 800x2000mm.pdf](https://github.com/stereocats/jenniferbrickwell/files/567160/Grasshopper.800x2000mm.pdf)
[Large-Format-Print-Guidelines.pdf](https://github.com/stereocats/jenniferbrickwell/files/567161/Large-Format-Print-Guidelines.pdf)

Image 1 (Would be good to get this version of the logo in an SVG format)
![jb-marketing-poster-logo](https://cloud.githubusercontent.com/assets/20337112/19938339/849a28a4-a11c-11e6-9eed-59beea6586f6.jpg)
Image 2 - photo of me as per business card.
Thanks for your help with this,

Jennifer

**Comment by iandstanley** [comment]
already is https://github.com/stereocats/jb-business-cards/blob/master/logo/exports/logo-with-tagline.svg

**Comment by iandstanley** [comment]
![sliced banner](https://cloud.githubusercontent.com/assets/6939289/19966840/76f68c52-a1c5-11e6-90b8-d6efc63e236e.jpg)

**Comment by iandstanley** [comment]
- switch logo and picture


- website 
- phone
- "Please contact me for a no obligation meeting to discuss your event"

**Comment by iandstanley** [comment]
![sliced banner](https://cloud.githubusercontent.com/assets/6939289/19974507/a48174aa-a1e0-11e6-8b47-9f0b8c219f4c.jpg)

**Comment by iandstanley** [comment]
- website on blue text in smaller type
![sliced banner](https://cloud.githubusercontent.com/assets/6939289/19975244/2c8b34f6-a1e3-11e6-943b-c0519abf9add.jpg)

**Comment by jenniferbrickwell** [comment]
Hi 
Sorry the printer would not work. Had a better look at the image. Key points:
1. Font and size to be consistent
2. Can we try with a blue banner at the bottom as well to match the blue halfway or black/grey, to create continuity. Thanks

**Comment by iandstanley** [comment]
![jennifer 800x2000mm clipped](https://cloud.githubusercontent.com/assets/6939289/19976645/7e1952ee-a1e8-11e6-93d7-676ff0bedf7b.jpg)

**Comment by iandstanley** [comment]
![jennifer 800x2000mm clipped](https://cloud.githubusercontent.com/assets/6939289/19976731/e92ef192-a1e8-11e6-81b0-5506152deb68.jpg)

**Comment by iandstanley** [comment]
![jennifer 800x2000mm clipped](https://cloud.githubusercontent.com/assets/6939289/19976956/b8889236-a1e9-11e6-9f84-bd436179bf91.jpg)

**Comment by iandstanley** [comment]
![jennifer 800x2000mm clipped](https://cloud.githubusercontent.com/assets/6939289/19977140/761acda0-a1ea-11e6-9e68-089f5706abb9.jpg)

**Comment by iandstanley** [comment]
![jennifer 800x2000mm clipped](https://cloud.githubusercontent.com/assets/6939289/19977223/cd9d791a-a1ea-11e6-9abe-17373895fbe6.jpg)

**Comment by iandstanley** [comment]
This issue was moved to JenniferBrickwellEvents/popup-banner#1
