### ISSUE TITLE
BLURB for Homepage: I need text & image for  (Jonathan Edwards?) testimony #1

### ISSUE THREAD

**Issue by iandstanley** [stereocats/jenniferbrickwell#70]
Probably Jonathan Edwards from Prospects

Jennifer is approaching him

**Comment by jenniferbrickwell** [comment]
Testimony from Ray-Fundraising Event guest
Great expression of vision and organisation for such an occasion. Provided a unique opportunity to meet with the future Mayor of Reading and also the local MP Rob Wilson.  The people who attended were thrilled that the event took place and new friendships were made. The range of cakes was tremendous!

**Comment by iandstanley** [comment]
Could you ask him for a photo?

**Comment by iandstanley** [comment]
I've added the prospects logo instead

**Comment by iandstanley** [comment]
Added into development copy

**Comment by jenniferbrickwell** [comment]
I am waiting for Jonathan's reply- he has just returned from holiday so I would hope to hear from him over the next week.
I just received this from Rob Wilson- I would prefer to use this and Jonathan's when it comes through. Perhaps use Ray's comments for the moment but please insert Rob's as well: 
Photo from https://www.robwilsonmp.com/news/rob-supports-prospects-cake-party
> I ’d like to thank Jennifer Brickwell at Prospects Ministry for inviting me to the cake party. This really is the Big Society in action.
> “It really felt like everyone was having a thoroughly enjoyable time, and with cakes and entertainment aplenty the event was a great success!”

_

**Comment by iandstanley** [comment]
put rob wilson text in testimony 1 - with his picture

**Comment by iandstanley** [comment]
put both rob and ray oin this section
