### ISSUE TITLE
Photo for (Kay Lane) testimony #2

### ISSUE THREAD

**Issue by iandstanley** [stereocats/jenniferbrickwell#71]
testimony for family events

**Comment by jenniferbrickwell** [comment]
Testimony from Bernard-  Special Family Birthday occasion

The arrangements had been planned well ahead of the birthday and done so from a distance. It was a delight to be present at the function where the venue, birthday menu and entertainment had been carefully planned; we felt it was a very happy and successful which everybody enjoyed.

**Comment by jenniferbrickwell** [comment]
Testimony from Charlie and Kay Lane
Bryan’s party was really well organised from the table seating, to the content of the party with even the young ones displaying their talent, to the piper accompanying the guest of honour as  he arrived.  It was a very happy occasion enjoyed by all.

**Comment by iandstanley** [comment]
Any photos for these people?

Photos draw people in and are more believable

**Comment by iandstanley** [comment]
Added to development copy

**Comment by jenniferbrickwell** [comment]
I have photos for these people. Just checking that they are OK with them.

**Comment by iandstanley** [comment]
Just need the photos when they are available .... reopening issue to keep track of this

**Comment by jenniferbrickwell** [comment]
Will confirm later today regarding photos. Presumably they are OK. Any problems let me know.
![bernard](https://cloud.githubusercontent.com/assets/20337112/17889274/3d09ce54-6927-11e6-8c91-279a023f3ee6.jpg)
![charlie and kay](https://cloud.githubusercontent.com/assets/20337112/17889275/3d0f1e5e-6927-11e6-9af3-fff1298fbd24.jpg)
